
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProfilesWSService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/ProfilesWSService/ProfilesWS?wsdl")
public class ProfilesWSService
    extends Service
{

    private final static URL PROFILESWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROFILESWSSERVICE_EXCEPTION;
    private final static QName PROFILESWSSERVICE_QNAME = new QName("http://ws/", "ProfilesWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ProfilesWSService/ProfilesWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFILESWSSERVICE_WSDL_LOCATION = url;
        PROFILESWSSERVICE_EXCEPTION = e;
    }

    public ProfilesWSService() {
        super(__getWsdlLocation(), PROFILESWSSERVICE_QNAME);
    }

    public ProfilesWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFILESWSSERVICE_QNAME, features);
    }

    public ProfilesWSService(URL wsdlLocation) {
        super(wsdlLocation, PROFILESWSSERVICE_QNAME);
    }

    public ProfilesWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFILESWSSERVICE_QNAME, features);
    }

    public ProfilesWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfilesWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProfilesWS
     */
    @WebEndpoint(name = "ProfilesWSPort")
    public ProfilesWS getProfilesWSPort() {
        return super.getPort(new QName("http://ws/", "ProfilesWSPort"), ProfilesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfilesWS
     */
    @WebEndpoint(name = "ProfilesWSPort")
    public ProfilesWS getProfilesWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "ProfilesWSPort"), ProfilesWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFILESWSSERVICE_EXCEPTION!= null) {
            throw PROFILESWSSERVICE_EXCEPTION;
        }
        return PROFILESWSSERVICE_WSDL_LOCATION;
    }

}
